version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      day: thursday # Used only on weekly interval
      time: "09:00"
      timezone: America/Chihuahua
    open-pull-requests-limit: 10
    reviewers: ["cetinajero"]
    labels:
      - dependencies
      - ruby

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: thursday # Used only on weekly interval
      time: "09:00"
      timezone: America/Chihuahua
    open-pull-requests-limit: 10
    reviewers: ["cetinajero"]
    labels:
      - dependencies
      - javascript
    ignore:
      - dependency-name: firebase
        versions:
          - ">= 7.9.a"
          - "< 7.10"
