os: linux
language: ruby
rvm:
  - 2.5.8

before_install:
  - gem install bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
  - bundle exec rake test:test
  - bundle exec rubocop
  - bundle exec rake test:html

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
