title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: Jekyll, GitHub Pages, theme, website, blog
lang: en_US

# Build settings
markdown: kramdown
remote_theme: cetinajero/jekyll-theme-marketing
plugins:
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-marketing.gemspec
  - LICENSE.txt
  - README.md
