title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "keywords:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: Jekyll, GitHub Pages, theme, website, blog
baseurl: /jekyll-theme-marketing
destination: ./_site/jekyll-theme-marketing
domain: jekyll.mx
original: true
lang: en_US
timezone: America/Chihuahua
google-analytics: UA-69457978-1
exchange-rates:
  usd: true
links:
  featured-product:
    565396f:
      disabled: true
product:
  price:
    disabled: # true # Disable the prices for the whole site
components:
  header: three-rows # Defines the header component
  ribbon: # disabled # Disable the whole component
    shoes-man: disabled # Disable a whole collection
    high-565396f3: disabled # Disable only on a product
special-offers:
  customers: true
social-media:
  - name: facebook
    link: https://www.facebook.com/
    plugin: https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgrupopvmx%2F&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=false&hide_cover=false&show_facepile=true&appId
  - name: youtube
    link: https://www.youtube.com/
  - name: twitter
    link: https://twitter.com/
  - name: linkedin
    link: https://mx.linkedin.com/
  - name: email
    link: /contact/

address:
  -
    name: "Matriz Chihuahua"
    street: "Calle Colegio No. 6300 Int 103"
    block: "Col. Cima Comercial"
    city: "Chihuahua, Chih., México"
    zip: "31216"
    phone:
      - { number: (614) 180 2929 }
    email: "contacto@grupopv.mx"
    custom-html:
    google-maps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3501.8545936139944!2d-106.123450!3d28.633913!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86ea42ce37814dcd%3A0x42787422e7151f85!2sGRUPO+PV!5e0!3m2!1ses-419!2smx!4v1467400506119"
  -
    name: "Matriz Chihuahua"
    street: "Calle Colegio No. 6300 Int 103"
    block: "Col. Cima Comercial"
    city: "Chihuahua, Chih., México"
    zip: "31216"
    phone:
      - { number: (614) 439 0707 }
    email: "contacto@grupopv.mx"
    custom-html:
    google-maps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3501.8545936139944!2d-106.123450!3d28.633913!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86ea42ce37814dcd%3A0x42787422e7151f85!2sGRUPO+PV!5e0!3m2!1ses-419!2smx!4v1467400506119"

css:
  bootstrap:
    primary: "#1A69D5"
  navbar:
    background-color: "#1A69D5"
  header:
    background-color: "#1A69D5"
  menu:
    font-color: "#FFF"
    icons: "#FFF"
  footer:
    top:
      background-color: "#1A69D5"
    bottom:
      background-color: "#F7F7F7"
      font-color: "#7F7F7F"
formspree:
  id: xeqpkezb
  cc: "email1@jekyll.com,email2@jekyll.com"
awards:
  -
    label: Kenny Davis Award 2014
    awards: ["award-2014"]
    type: Kenny Davis Award
  -
    label: Store Manager of the year 2015
    awards: ["award-2015"]
    type: Store manager

collections:
  pages:
    output: true
    permalink: /:path/
    products:
      detail: true
  shoes-woman:
    output: true
    permalink: /:collection/:categories/:name/
    products:
      detail: true
  shoes-man:
    output: true
    permalink: /:collection/:categories/:name/
    prices: false # Disable the prices for the whole collection
    products:
      detail: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: page
      published: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      image: https://s3-us-west-2.amazonaws.com/grupopv-public/components/logos/progressive/img/grupopv-og.png
      published: true
  -
    scope:
      path: ""
      type: "shoes-woman"
    values:
      layout: product
      published: true
  -
    scope:
      path: ""
      type: "shoes-man"
    values:
      layout: product
      published: true

amazon-s3: https://grupopv-public.s3.amazonaws.com
permalink: /:categories/:title/
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Build settings
markdown: kramdown
remote_theme: cetinajero/jekyll-theme-marketing
plugins:
  - jekyll-remote-theme
exclude:
  - lib
  - tests
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - jekyll-theme-marketing.gemspec
  - package.json
  - yarn.lock
  - LICENSE
  - README.md
  - CHANGELOG.md
  - CODEOWNERS
  - vendor
