<div id="javascript">
  <!-- 3D Space product card -->
  <script src="/assets/js/product-cards/3d-space.js"></script>

  <script src="{{ '/assets/node_modules/bootstrap/dist/js/bootstrap.min.js' | relative_url }}"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/jshashtable-2.1_src.js"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/jquery.numberformatter-1.2.3.js"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/tmpl.js"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/jquery.dependClass-0.1.js"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/draggable-0.1.js"></script>
  <script src="/vendors/themes/vg_progressive/js/price-regulator/jquery.slider.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.carouFredSel-6.2.1-packed.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.touchSwipe.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.elevateZoom-3.0.8.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.imagesloaded.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.appear.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.sparkline.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.easypiechart.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.easing.1.3.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.fancybox.pack.js"></script>
  <script src="/vendors/themes/vg_progressive/js/isotope.pkgd.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.knob.js"></script>
  <script src="{{ '/assets/node_modules/jquery.stellar/jquery.stellar.min.js' | relative_url }}"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.selectBox.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jquery.tubular.1.0.js"></script>
  <script src="/vendors/themes/vg_progressive/js/SmoothScroll.js"></script>
  <script src="/vendors/themes/vg_progressive/js/country.js"></script>
  <script src="/vendors/themes/vg_progressive/js/spin.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/ladda.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/masonry.pkgd.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/morris.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/raphael.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/video.js"></script>
  <script src="/vendors/themes/vg_progressive/js/pixastic.custom.js"></script>
  <script src="/vendors/themes/vg_progressive/js/livicons-1.3.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/bootstrapValidator.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/bootstrap-datepicker.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jplayer/jquery.jplayer.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/jplayer/jplayer.playlist.min.js"></script>
  <script src="/vendors/themes/vg_progressive/js/main.js"></script>
</div>
