version: 1

update_configs:

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["cetinajero"]
    default_labels:
      - "dependencies"
      - "javascript"

  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["cetinajero"]
    default_labels:
      - "dependencies"
      - "ruby"
    automerged_updates:
      - match:
          dependency_name: "*"
